spring:
  datasource:
    name: hospital
    url: jdbc:mysql://localhost:3306/hospital?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  resources:
    static-locations: classpath:/
server:
  port: 9090
mybatis:
  type-aliases-package: com.hospitaldatacenter.entity
  mapper-locations: classpath:mapper/*.xml
