spring:
  datasource:
    name: hospital
    url: jdbc:mysql://192.168.0.120:3306/hospital?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  redis:
    host: localhost
    port: 6379
    timeout: 10s
  resources:
    static-locations: classpath:/
server:
  port: 9090
mybatis:
  type-aliases-package: com.hospitaldatacenter.entity
  mapper-locations: classpath:mapper/*.xml
